import 'package:flutter/material.dart';
import 'package:iyc/app/core/app_export.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  final _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  final Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  final Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    PrefUtils().setThemeData(_newTheme);
    Get.forceAppUpdate();
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        // _supportedColorScheme[_appTheme] ??
            ColorSchemes.primaryColorScheme;
    return ThemeData(
      useMaterial3:true,
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: Colors.white,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(20.h),
          ),
          shadowColor: appTheme.cyan50,
          elevation: 8,
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: appTheme.blue10001,
            width: 1.h,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(20.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      checkboxTheme: CheckboxThemeData(
        fillColor: MaterialStateColor.resolveWith((states) {
          if (states.contains(MaterialState.selected)) {
            return colorScheme.primary;
          }
          return colorScheme.onSurface;
        }),
        side: const BorderSide(
          width: 1,
        ),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 1,
        space: 1,
        color: appTheme.blue10001,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
    bodyLarge: TextStyle(
      color: appTheme.blueGray70001,
      fontSize: 16.fSize,
      fontFamily: 'Be Vietnam Pro',
      fontWeight: FontWeight.w400,
    ),
    bodyMedium: TextStyle(
      color: appTheme.blueGray300,
      fontSize: 14.fSize,
      fontFamily: 'Be Vietnam Pro',
      fontWeight: FontWeight.w400,
    ),
    bodySmall: TextStyle(
      color: appTheme.blueGray70001,
      fontSize: 12.fSize,
      fontFamily: 'Be Vietnam Pro',
      fontWeight: FontWeight.w400,
    ),
    displaySmall: TextStyle(
      color: colorScheme.onPrimaryContainer.withOpacity(1),
      fontSize: 36.fSize,
      fontFamily: 'Nunito',
      fontWeight: FontWeight.w800,
    ),
    headlineMedium: TextStyle(
      color: colorScheme.onPrimaryContainer.withOpacity(1),
      fontSize: 28.fSize,
      fontFamily: 'Be Vietnam Pro',
      fontWeight: FontWeight.w600,
    ),
    headlineSmall: TextStyle(
      color: colorScheme.onPrimaryContainer.withOpacity(1),
      fontSize: 24.fSize,
      fontFamily: 'Be Vietnam Pro',
      fontWeight: FontWeight.w600,
    ),
    labelLarge: TextStyle(
      color: appTheme.deepPurple600,
      fontSize: 13.fSize,
      fontFamily: 'Poppins',
      fontWeight: FontWeight.w600,
    ),
    labelMedium: TextStyle(
      color: appTheme.black900,
      fontSize: 10.fSize,
      fontFamily: 'Poppins',
      fontWeight: FontWeight.w600,
    ),
    titleLarge: TextStyle(
      color: appTheme.indigo800,
      fontSize: 20.fSize,
      fontFamily: 'Be Vietnam Pro',
      fontWeight: FontWeight.w600,
    ),
    titleMedium: TextStyle(
      color: appTheme.indigo800,
      fontSize: 16.fSize,
      fontFamily: 'Be Vietnam Pro',
      fontWeight: FontWeight.w600,
    ),
    titleSmall: TextStyle(
      color: appTheme.amber600,
      fontSize: 14.fSize,
      fontFamily: 'Poppins',
      fontWeight: FontWeight.w600,
    ),
  );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static const primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF85DEEE),
    primaryContainer: Color(0XFF263238),
    secondary: Color(0XFF263238),
    secondaryContainer: Color(0X1EA2A9B3),
    tertiary: Color(0XFF263238),
    tertiaryContainer: Color(0X1EA2A9B3),

    // Background colors
    background: Color(0XFF263238),

    // Surface colors
    surface: Color(0XFF263238),
    surfaceTint: Color(0XFF1F1F1F),
    surfaceVariant: Color(0X1EA2A9B3),

    // Error colors
    error: Color(0XFF1F1F1F),
    errorContainer: Color(0XFF6B8099),
    onError: Color(0XFFB9B1F0),
    onErrorContainer: Color(0XFF2A0845),

    // On colors(text colors)
    onBackground: Color(0X99FFFFFF),
    onInverseSurface: Color(0XFFB9B1F0),
    onPrimary: Color(0XFF1F1F1F),
    onPrimaryContainer: Color(0X99FFFFFF),
    onSecondary: Color(0X99FFFFFF),
    onSecondaryContainer: Color(0XFF1F1F1F),
    onTertiary: Color(0X99FFFFFF),
    onTertiaryContainer: Color(0XFF1F1F1F),

    // Other colors
    outline: Color(0XFF1F1F1F),
    // outlineVariant: Color(0XFF263238),
    // scrim: Color(0XFF263238),
    shadow: Color(0XFF1F1F1F),

    // Inverse colors
    inversePrimary: Color(0XFF263238),
    inverseSurface: Color(0XFF1F1F1F),

    // Pending colors
    onSurface: Color(0X99FFFFFF),
    onSurfaceVariant: Color(0XFF1F1F1F),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Amber
  Color get amber600 => const Color(0XFFFFB700);
  Color get amber800 => const Color(0XFFFF8E0E);
  Color get amberA200 => const Color(0XFFFED843);
  Color get amberA400 => const Color(0XFFFFC100);
  Color get amberA700 => const Color(0XFFFFA904);

  // Black
  Color get black900 => const Color(0XFF000000);

  // Blue
  Color get blue100 => const Color(0XFFD2D9FF);
  Color get blue10001 => const Color(0XFFC0D5F3);
  Color get blue10002 => const Color(0XFFC4D0FB);
  Color get blue50 => const Color(0XFFE9F2FF);
  Color get blue5001 => const Color(0XFFD2E4FF);
  Color get blue5002 => const Color(0XFFE9F1FF);
  Color get blue5003 => const Color(0XFFD9E8FE);
  Color get blue700 => const Color(0XFF005BEA);
  Color get blue800 => const Color(0XFF2160C3);
  Color get blue80001 => const Color(0XFF1356BF);
  Color get blue80002 => const Color(0XFF1455BB);
  Color get blue80003 => const Color(0XFF1957B3);
  Color get blueA200 => const Color(0XFF458EFF);

  // BlueGray
  Color get blueGray300 => const Color(0XFF869DB6);
  Color get blueGray400 => const Color(0XFF748AA2);
  Color get blueGray40001 => const Color(0XFF858494);
  Color get blueGray40002 => const Color(0XFF888888);
  Color get blueGray700 => const Color(0XFF4F565E);
  Color get blueGray70001 => const Color(0XFF365B85);
  Color get blueGray900 => const Color(0XFF292F3B);

  // Cyan
  Color get cyan200 => const Color(0XFF85DEEE);
  Color get cyan50 => const Color(0XFFD6F9FF);
  Color get cyan600 => const Color(0XFF0CA0BA);
  Color get cyan60001 => const Color(0XFF0CA0B9);
  Color get cyanA400 => const Color(0XFF0FDEEA);

  // DeepOrange
  Color get deepOrange400 => const Color(0XFFFA894A);
  Color get deepOrange800 => const Color(0XFFDA4321);
  Color get deepOrangeA200 => const Color(0XFFFF6536);
  Color get deepOrangeA700 => const Color(0XFFE61818);

  // DeepPurple
  Color get deepPurple400 => const Color(0XFF6A5AE0);
  Color get deepPurple40001 => const Color(0XFF805AC6);
  Color get deepPurple40002 => const Color(0XFF8059C5);
  Color get deepPurple600 => const Color(0XFF613FA0);
  Color get deepPurple60001 => const Color(0XFF6441A5);
  Color get deepPurple700 => const Color(0XFF55378D);

  // Gray
  Color get gray100 => const Color(0XFFF0FCF8);
  Color get gray10001 => const Color(0XFFEFF1FE);
  Color get gray200 => const Color(0XFFE7E7E7);
  Color get gray20001 => const Color(0XFFF2F0F0);
  Color get gray300 => const Color(0XFFE6E6E6);
  Color get gray30000 => const Color(0X00E2E2E2);
  Color get gray50 => const Color(0XFFF9FAFA);
  Color get gray500 => const Color(0XFF9E9E9E);
  Color get gray5001 => const Color(0XFFF8FAFF);
  Color get gray600 => const Color(0XFF6D6D6D);
  Color get gray700 => const Color(0XFF555555);
  Color get gray800 => const Color(0XFF404040);
  Color get gray900 => const Color(0XFF001833);
  Color get gray90001 => const Color(0XFF030747);
  Color get gray90002 => const Color(0XFF030747);

  // Green
  Color get green300 => const Color(0XFF84DE8D);
  Color get green500 => const Color(0XFF39A85E);

  // Indigo
  Color get indigo100 => const Color(0XFFB1C8E2);
  Color get indigo10001 => const Color(0XFFC3D5F0);
  Color get indigo10002 => const Color(0XFFB5BCEA);
  Color get indigo10003 => const Color(0XFFB5BBE9);
  Color get indigo50 => const Color(0XFFEAECFC);
  Color get indigo500 => const Color(0XFF3A59C4);
  Color get indigo5001 => const Color(0XFFE1E4F9);
  Color get indigo5002 => const Color(0XFFE2E4FA);
  Color get indigo700 => const Color(0XFF263DAB);
  Color get indigo800 => const Color(0XFF244974);
  Color get indigo80001 => const Color(0XFF274C77);

  // LightGreen
  Color get lightGreen200 => const Color(0XFFD9C998);

  // Lime
  Color get lime100 => const Color(0XFFF2EAD4);

  // Orange
  Color get orange400 => const Color(0XFFFFAB2A);
  Color get orange40001 => const Color(0XFFFFA625);
  Color get orange50 => const Color(0XFFF2EBD5);
  Color get orangeA700 => const Color(0XFFFF6D04);

  // Pink
  Color get pink100 => const Color(0XFFF5BEC7);
  Color get pink10001 => const Color(0XFFFFC0DE);
  Color get pink50 => const Color(0XFFFCDBDF);

  // Red
  Color get red100 => const Color(0XFFF2D1D7);
  Color get red10001 => const Color(0XFFF2D2D7);
  Color get red200 => const Color(0XFFDA9EA8);
  Color get red20001 => const Color(0XFFD99DA7);
  Color get red50 => const Color(0XFFFDF1F3);
  Color get red600 => const Color(0XFFDD2E44);
  Color get redA700 => const Color(0XFFE60000);

  // Teal
  Color get teal200 => const Color(0XFF94D3BE);
  Color get teal400 => const Color(0XFF36B37E);
  Color get teal50 => const Color(0XFFD1F2E8);
  Color get teal5001 => const Color(0XFFD8E5F8);
  Color get teal5002 => const Color(0XFFD0F2E8);

  // Yellow
  Color get yellow50 => const Color(0XFFFFFBEF);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();