// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASMGpYYV1KumZXkukFphFeKdkGnBU3YZU',
    appId: '1:621348065220:web:9698c62aa8788c4d96de91',
    messagingSenderId: '621348065220',
    projectId: 'proven-entropy-396604',
    authDomain: 'proven-entropy-396604.firebaseapp.com',
    storageBucket: 'proven-entropy-396604.appspot.com',
    measurementId: 'G-08TZ3ZGD95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSojzoYFjwCB7Lf0DMSnJMaHBeBm5G-Xs',
    appId: '1:621348065220:android:645d23331ca09e4896de91',
    messagingSenderId: '621348065220',
    projectId: 'proven-entropy-396604',
    storageBucket: 'proven-entropy-396604.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxmG1H_cTAcA7tkfqb9tVAHzyiQ4GCDpA',
    appId: '1:621348065220:ios:4ccbc666be0acceb96de91',
    messagingSenderId: '621348065220',
    projectId: 'proven-entropy-396604',
    storageBucket: 'proven-entropy-396604.appspot.com',
    iosBundleId: 'com.brighterindia.iyc',
  );

  //com.bif.*iyc
  //com.*brighterindia.iyc

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxmG1H_cTAcA7tkfqb9tVAHzyiQ4GCDpA',
    appId: '1:621348065220:ios:757a4d6d87a3213496de91',
    messagingSenderId: '621348065220',
    projectId: 'proven-entropy-396604',
    storageBucket: 'proven-entropy-396604.appspot.com',
    iosBundleId: 'com.example.withiycnew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5jIVbyoaylE5TgXPH2V7ySpLTtf66mPM',
    appId: '1:621348065220:web:3e24cc98b904122696de91',
    messagingSenderId: '621348065220',
    projectId: 'proven-entropy-396604',
    authDomain: 'proven-entropy-396604.firebaseapp.com',
    storageBucket: 'proven-entropy-396604.appspot.com',
    measurementId: 'G-3VQM9YR22Y',
  );

}